source = ./colors.conf

wallpaper {
	monitor = eDP-2
	path = $wallpaper
}

wallpaper {
	monitor = DP-9
	path = $wallpaper
}

wallpaper {
	monitor = eDP-1
	path = $wallpaper
}

wallpaper {
	monitor = DP-1
	path = $wallpaper
}
