########################
### HYPRLAND MODULES ###
########################

source = ./modules/plugins.conf
source = ./colors.conf
source = ./modules/defaults.conf
source = ./modules/envs.conf
source = ./modules/monitors.conf
source = ./modules/autostart.conf
source = ./modules/binds.conf
source = ./modules/HIDs.conf
source = ./modules/windowrules.conf
source = ./modules/visuals.conf
