#########################
### DEFAULT VARIABLES ###
#########################

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$lockscreenManager = hyprlock
$colorPicker = hyprpicker -a
$screenCap = grim -g "$(slurp -w 0)" - | wl-copy
$screenRec = wf-recorder-gui
$OCR = grim -g "$(slurp)" - | tesseract - - -l eng+rus+ara+heb+hin+chi_sim+chi_tra+jpn+kor+tha+ell+amh+tam+equ | wl-copy
$menu = wofi --show drun
$emojiPicker = wofi-emoji
$clipHist = cliphist list | wofi --dmenu | cliphist decode | wl-copy
$mainMon = DP-9
$lapMon = eDP-1
$hypr = $HOME/.config/hypr
$layoutSwitcher = $hypr/scripts/toggle_layout.sh
