#################
### AUTOSTART ###
#################

exec-once = waybar & hyprpaper & steam -silent # foreground
exec-once = hypridle & kdeconnectd & cliphist wipe # background
exec-once = xrandr --output $mainMon --primary
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = hyprctl dispatch exec "[workspace 1]" kitty
exec-once = hyprctl dispatch exec "[workspace 2 silent]" zen-browser
exec-once = hyprctl dispatch exec "[workspace 3 silent]" "/usr/bin/vesktop %U vesktop --enable-features=UseOzonePlatform --ozone-platform=auto --enable-blink-features=MiddleClickAutoscroll"
exec-once = hyprctl dispatch exec "[workspace 10 silent]" "kitty -e btop"

 # xwaylandvideobridge & is removed as its not needed anymore
