#########################
### DEFAULT VARIABLES ###
#########################
$hypr = $HOME/.config/hypr

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$lockscreenManager = hyprlock
$colorPicker = hyprpicker -a
$screenCap = $hypr/scripts/scnshot_notify.sh
$screenRec = wf-recorder-gui
$OCR = grim -g "$(slurp)" - | tesseract - - -l eng+rus+ara+heb+hin+chi_sim+chi_tra+jpn+kor+tha+ell+amh+tam+equ | wl-copy
$menu = rofi -show drun
$emojiPicker = rofi -show emoji
$clipHist = cliphist list | rofi -dmenu -p "󱃕 Clipboard" -display-columns 2 | cliphist decode | wl-copy
$mainMon = DP-9
$lapMon = eDP-1
$layoutSwitcher = $hypr/scripts/toggle_layout.sh
